services:
  carmar-intranet-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: carmar/frontend:latest
    container_name: carmar-intranet-frontend
    ports:
      - "8989:8080"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
